/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as HistoryImport } from './routes/history'
import { Route as AuthFormImport } from './routes/authForm'
import { Route as AddEarningsImport } from './routes/addEarnings'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const HistoryRoute = HistoryImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRoute,
} as any)

const AuthFormRoute = AuthFormImport.update({
  id: '/authForm',
  path: '/authForm',
  getParentRoute: () => rootRoute,
} as any)

const AddEarningsRoute = AddEarningsImport.update({
  id: '/addEarnings',
  path: '/addEarnings',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/addEarnings': {
      id: '/addEarnings'
      path: '/addEarnings'
      fullPath: '/addEarnings'
      preLoaderRoute: typeof AddEarningsImport
      parentRoute: typeof rootRoute
    }
    '/authForm': {
      id: '/authForm'
      path: '/authForm'
      fullPath: '/authForm'
      preLoaderRoute: typeof AuthFormImport
      parentRoute: typeof rootRoute
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addEarnings': typeof AddEarningsRoute
  '/authForm': typeof AuthFormRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addEarnings': typeof AddEarningsRoute
  '/authForm': typeof AuthFormRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/addEarnings': typeof AddEarningsRoute
  '/authForm': typeof AuthFormRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/addEarnings' | '/authForm' | '/history' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/addEarnings' | '/authForm' | '/history' | '/settings'
  id: '__root__' | '/' | '/addEarnings' | '/authForm' | '/history' | '/settings'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddEarningsRoute: typeof AddEarningsRoute
  AuthFormRoute: typeof AuthFormRoute
  HistoryRoute: typeof HistoryRoute
  SettingsRoute: typeof SettingsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddEarningsRoute: AddEarningsRoute,
  AuthFormRoute: AuthFormRoute,
  HistoryRoute: HistoryRoute,
  SettingsRoute: SettingsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/addEarnings",
        "/authForm",
        "/history",
        "/settings"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/addEarnings": {
      "filePath": "addEarnings.tsx"
    },
    "/authForm": {
      "filePath": "authForm.tsx"
    },
    "/history": {
      "filePath": "history.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
